### ISSUE TITLE
Update main docs for new CDK implementation

### ISSUE THREAD

**Issue by doctorray117** [doctorray117/minecraft-ondemand#20]
I want to highlight it as an easy way to get up and running quickly while leaving the full docs for anyone who desires to learn more about how all this stuff works in AWS.  Will be working on it between work items this week.

**Comment by AleesJaved** [comment]
Please could you add an easy way for novices to do this. I really want to do it but I have no idea how to. Thanks

**Comment by doctorray117** [comment]
I've been looking into doing this but haven't had time to wrap it up. I'll see if I can get something out over the weekend... Please check back later.

**Comment by AleesJaved** [comment]
Ok cool thanks for the reply!

**Comment by doctorray117** [comment]
Good news, I even got it deploying from Windows in just a few easy steps.  branched to update docs, and plan to have it up over the weekend.

**Comment by AleesJaved** [comment]
Sorry to be rude but is it close to done yet? I really want to get this for a server I am making.

**Comment by doctorray117** [comment]
https://github.com/doctorray117/minecraft-ondemand/tree/feature/cdk-updates/cdk

^^ see above.  Work in progress but the steps are good, and I've tested them from Windows.  The document needs a little bit more cleanup.  Feel free to try it out and provide any feedback on what may be unclear.
