### ISSUE TITLE
Lambda watchdog

### ISSUE THREAD

**Issue by binarythinktank** [doctorray117/minecraft-ondemand#22]
Hi
This is a fun project :) 

I have 3 questions

1. Could the Watchdog not run in a Lambda? triggered every 10 minutes or so by EventBridge schedule that is created by the error handling lambda (and deleted again when the container is terminated)? This should further optimise cost and make it more serverless.

2. This is not a scaling solution, right? it is 1 container that needs to be big enough for the expected number of users.

3. if the container is launched after a hit on the domain name, at some point you will get a lot of false positives from bots and such, right? is there a (serverless) way to make sure it's a Minecraft client asking for the link before launching anything? 

thanks!

**Comment by doctorray117** [comment]
The issue with the api gateway is that it won't listen on the minecraft listening port on the front-end, so there'd be no way to trigger it without manually hitting another URL.  I'll reply to your other questions soon, still working today :)

**Comment by binarythinktank** [comment]
ah, right. and port conversion needs non-serverless components in front of it :/

**Comment by binarythinktank** [comment]
many thanks, those are good points. Going to try and launch it this weekend and play around with it!
