### ISSUE TITLE
Issue with CDK v2

### ISSUE THREAD

**Issue by LucaSoato** [doctorray117/minecraft-ondemand#23]
Hi, 
I've deployed the CDK stack to my account this weekend but it was much more complicated than expected.
This sadly was caused by the recent AWS transition to the version 2 of CDK bootstrapping module.
To make it work, remember to export the `CDK_NEW_BOOTSTRAP` environment variable:
```shell
export CDK_NEW_BOOTSTRAP=1
```
If you agree I can create a PR, adding this in the documentation. 
Thanks for the help and thank you again for this awesome piece of art. 
Hosting a serverless Minecraft server is so cool :)

**Comment by ryansonshine** [comment]
@LucaSoato, thanks for the feedback. Yes I think this would be a great addition to the documentation and we can also add it to the deploy command in `package.json`. PR welcome.

**Comment by doctorray117** [comment]
@ryansonshine do you think this var is required?  I was able to deploy without it in testing while writing updating documentation.  Looking to close this issue either way.  Thanks.

**Comment by ryansonshine** [comment]
> @ryansonshine do you think this var is required?  I was able to deploy without it in testing while writing updating documentation.  Looking to close this issue either way.  Thanks.

For new users to CDK it won't be required but for anyone who may have used older versions of CDK I think it would be a good idea to add. Both sets of users can have the env var set.

Might be worth implementing with the [cross-env](https://www.npmjs.com/package/cross-env) to make sure we're covering Windows users.

**Comment by doctorray117** [comment]
Incorporated the env variable within the default env file in the advanced section so that it's there by default.
