### ISSUE TITLE
Migrate to terraform?

### ISSUE THREAD

**Issue by tom-sherman** [doctorray117/minecraft-ondemand#3]
This would make the 400ln install process as simple as calling `terraform apply`

**Comment by spscally** [comment]
[AWS CDK](https://aws.amazon.com/cdk/) might be a good option too

**Comment by deploystudios** [comment]
I'm going to take a stab at terraforming this. I'll post back and PR if/when I get it sorted out.

**Comment by doctorray117** [comment]
Awesome, yeah cdk or terraform would be a great add-on option.  I'm barely starting to dip my toes into both.  Please let me know if you have any success, I'd love to add it in.  What I wasn't too sure on was configuring it so that a user could select between resource reuse (like vpc's, etc) or creating all new.

**Comment by duaneking** [comment]
I think making this a simple cloud formation script would be the best, given that it's AWS only￼.

The problem with terraform is that it holds state locally; It's also not as compatible with aws as cloud formation is.

**Comment by deploystudios** [comment]
@duaneking great point. CF also gives you a visual stack you can have instructions to turn off/delete.

Once i get a resource map sorted out, I'll see how hard it would be to do both.

**Comment by gchamon** [comment]
> The problem with terraform is that it holds state locally; 

you can use an S3 bucket to hold state. Yes this has to be created manually, but so would be applying a cloudformation stack. Terraform has the benefit of previewing changes and being much more dev friendly.

**Comment by JKolios** [comment]
I've gone ahead and written a quick Terraform implementation in https://github.com/JKolios/minecraft-ondemand-terraform. I don't believe it's PR-ready yet, but it might be interesting to hack around with. Comments and contributions are of course welcome. Also, please tell me if there are any licensing or attribution issues.

**Comment by ryansonshine** [comment]
A CDK implementation is in progress

**Comment by ryansonshine** [comment]
A CDK Implementation is in progress, this will also give us the ability to create a "one-click" CloudFormation version for users who aren't as familiar with AWS.

**Comment by ryansonshine** [comment]
I'm currently working on a CDK Implementation, this will also give us the ability to create a "one-click" CloudFormation version for users who aren't as familiar with AWS. Opened https://github.com/doctorray117/minecraft-ondemand/issues/8 for tracking

**Comment by mphuff** [comment]
> I've gone ahead and written a quick Terraform implementation in https://github.com/JKolios/minecraft-ondemand-terraform. I don't believe it's PR-ready yet, but it might be interesting to hack around with. Comments and contributions are of course welcome. Also, please tell me if there are any licensing or attribution issues.

I used this and works like an absolute charm - one CLI call to roll it all out! Great job @JKolios - I may submit a PR to you with a few minor mods I've made along the way.

**Comment by doctorray117** [comment]
@mphuff and @JKolios please note slight adjustment to docs with modifying EFS security group to allow access from ECS resources; docs point to modification of default security group to allow nfs from vpc, though when terraforming a dedicated security group added to the efs mounts would likely be preferable.

Definitely interested in including and supporting both terraform and cdk deployment options within the project if you're willing to contribute what you've done, I'm happy to help test as I want to learn how all that works anyway and this would be a good way to do that while testing your code.

**Comment by doctorray117** [comment]
Closing issue as CDK deployment is working well, with documentation currently being expanded.
