### ISSUE TITLE
How to restart the server without waiting 20 minutes?

### ISSUE THREAD

**Issue by AdamMarciniak** [doctorray117/minecraft-ondemand#30]
I was able to get the EFS stuff working with editing files but I'd like to restart the server to see my changes. How do I do that without waiting 20 minutes?

**Comment by doctorray117** [comment]
The easiest way would be to open the ECS console, select the cluster, then the service, then the task, and select "stop". This will set the desired count to zero and you can start again.

**Comment by AdamMarciniak** [comment]
Thanks!
