### ISSUE TITLE
Incremental config changes?

### ISSUE THREAD

**Issue by orange2008** [doctorray117/minecraft-ondemand#47]
I didn't try, but if I want to change some settings, like Twilio keys or the vCPUs and RAM. Do I need to change the `.env` files and run `npm run build && npm run deploy`? I haven't tried that yet, but I am worrying about that it's going to create a new stack and a completely new server? **Or maybe I was wrong?**

**Comment by ryansonshine** [comment]
Hi @orange2008 ,

Yes, you'll want to change the variables in `.env` and run the build and deploy commands again. Your existing resources will be updated instead of creating new ones.

**Comment by ryansonshine** [comment]
Closing but feel free to reopen if that didn't resolve your issue.
