### ISSUE TITLE
DataSync step 2 is invalid

### ISSUE THREAD

**Issue by Ponjimon** [doctorray117/minecraft-ondemand#50]
According to the step-by-step:

```
Includes for Java edition: add three:
*.json (this will include banned-ips, banned-players, ops, usercache, whitelist)
```

but the problem is that, despite AWS describing this in their own documentation, it's not possible to define file patterns like this because:

![image](https://user-images.githubusercontent.com/770632/170836938-99215e01-8c43-46d0-b695-07998377447c.png)

Unless I'm doing something completely wrong here?

**Comment by doctorray117** [comment]
Good catch.  I was thinking about spending some time on issues this weekend so I'll update from this.  As a workaround, you can specify each of the exact json files needed instead.

My test folder is a little out of date but the json files I see specifically are:
```
banned-ips.json
banned-players.json
ops.json
usercache.json
whitelist.json
```

**Comment by Ponjimon** [comment]
Thanks, good to know I was not doing something wrong :D 

I assume I would have to sync the `plugins/` folder too, if I wanted to add some?

**Comment by doctorray117** [comment]
It may be easiest just to turn sync on for the whole thing.  Also please look at issue #48 as there is a permissions issue when copying back from S3 to EFS.

For plugins, you might take a look at the minecraft docker image documentation, there's a bunch you can do with environmental variables.
